DROP EXTENSION IF EXISTS pg_ta;
CREATE EXTENSION pg_ta;

DROP TABLE IF EXISTS sma;
CREATE TABLE sma (
    value double precision,
    id integer NOT NULL
);

ALTER TABLE ONLY sma ADD CONSTRAINT sma_pkey PRIMARY KEY (id);

INSERT INTO sma VALUES (5, 1);
INSERT INTO sma VALUES (1, 2);
INSERT INTO sma VALUES (1, 3);
INSERT INTO sma VALUES (5, 4);
INSERT INTO sma VALUES (10, 5);
INSERT INTO sma VALUES (11, 6);
INSERT INTO sma VALUES (13, 7);
INSERT INTO sma VALUES (14, 8);
INSERT INTO sma VALUES (15, 9);
INSERT INTO sma VALUES (8, 10);
INSERT INTO sma VALUES (2, 11);
INSERT INTO sma VALUES (3, 12);
INSERT INTO sma VALUES (8, 13);
INSERT INTO sma VALUES (5, 14);
INSERT INTO sma VALUES (4, 15);
INSERT INTO sma VALUES (3, 16);
INSERT INTO sma VALUES (2, 17);
INSERT INTO sma VALUES (1, 18);
INSERT INTO sma VALUES (1, 19);
INSERT INTO sma VALUES (1, 20);

SELECT ta_f(ARRAY(SELECT value FROM sma));
